export const servicesData = [
  { id: 1, title: "Gumasta Registration", price: "₹1,499", desc: "Shop and Establishment Act Registration." },
  { id: 2, title: "Udyam Aadhar", price: "₹499", desc: "MSME registration for your business." },
  { id: 3, title: "Food License (FSSAI)", price: "₹1,999", desc: "Mandatory for all food-related businesses." },
  { id: 4, title: "Import Export Code", price: "₹2,499", desc: "Required for international trade." },
  { id: 5, title: "Trade License", price: "₹3,499", desc: "Local municipal corporation license." },
  { id: 6, title: "ISO Certification", price: "₹4,999", desc: "Quality management systems certification." },
  { id: 7, title: "PF Registration", price: "₹2,999", desc: "Provident Fund registration for employees." },
  { id: 8, title: "ESIC Registration", price: "₹2,999", desc: "Employee State Insurance Corporation registration." },
  { id: 9, title: "Professional Tax", price: "₹1,499", desc: "State-level tax on professionals." },
  { id: 10, title: "Company Incorporation", price: "₹9,999", desc: "Pvt Ltd, LLP, or OPC registration." },
  { id: 11, title: "GST Registration", price: "₹1,499", desc: "Goods and Services Tax registration." },
  { id: 12, title: "Income Tax Return", price: "₹999", desc: "Annual ITR filing services." },
  { id: 13, title: "TDS Return", price: "₹1,499", desc: "Quarterly TDS return filing." },
  { id: 14, title: "Accounting Services", price: "Custom", desc: "Monthly bookkeeping and accounting." },
  { id: 15, title: "Trademark Registration", price: "₹5,999", desc: "Protect your brand identity." },
  { id: 16, title: "Copyright Registration", price: "₹4,999", desc: "Protect your creative work." },
  { id: 17, title: "Patent Filing", price: "Custom", desc: "Protect your inventions." },
  { id: 18, title: "Legal Drafting", price: "Custom", desc: "Agreements, contracts, and legal notices." },
  { id: 19, title: "Pan Card", price: "₹199", desc: "New application and corrections." },
  { id: 20, title: "Passport Application", price: "₹1,499", desc: "New and renewal applications." },
  { id: 21, title: "Digital Signature", price: "₹999", desc: "Class 3 DSC with token." },
  { id: 22, title: "Rent Agreement", price: "₹499", desc: "Registered rent agreements." },
  { id: 23, title: "Affidavits", price: "₹299", desc: "All types of affidavits and declarations." },
  { id: 24, title: "Marriage Registration", price: "₹2,499", desc: "Court marriage and registration." },
  { id: 25, title: "Name Change", price: "₹1,999", desc: "Gazette notification for name change." },
  { id: 26, title: "RERA Registration", price: "Custom", desc: "For real estate projects and agents." },
  { id: 27, title: "Firma Registration", price: "₹2,499", desc: "Partnership firm registration." },
  { id: 28, title: "Trust Registration", price: "₹8,999", desc: "NGO, Trust, and Society registration." },
  { id: 29, title: "Startup India", price: "₹4,999", desc: "DPIIT recognition for startups." }
];
